services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: dbviewer_node
    container_name: dbviewer_node
    ports: 
    - "5000:5000"
    restart: unless-stopped
    volumes:
    - ./:/usr/src/app